version: "3.4"

services:
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    env_file: .env
    depends_on:
      - db
