name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Test backend
        run: |
          cd backend
          yarn install
          yarn test

      - name: Test frontend
        run: |
          cd frontend
          yarn install
          yarn test --verbose
